version: '3.8'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /mnt/usb:/mnt/usb
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/tauri
      - TMP_UPLOAD_DIR=/tmp/tauri_uploads
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tauri
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
